/** Expanded phone catalog for global defaults. */

export type ExpandedCatalogBrand = {
  name: string;
  sortOrder: number;
  families: string[];
};

export const EXPANDED_PHONE_CATALOG: ExpandedCatalogBrand[] = [
  {
    name: "Apple",
    sortOrder: 1,
    families: [
      "iPhone 17 Pro Max",
      "iPhone 17 Pro",
      "iPhone 17",
      "iPhone Air",
      "iPhone 17e",
      "iPhone 16e",
      "iPhone 16 Pro Max",
      "iPhone 16 Pro",
      "iPhone 16 Plus",
      "iPhone 16",
      "iPhone 15 Pro Max",
      "iPhone 15 Pro",
      "iPhone 15 Plus",
      "iPhone 15",
      "iPhone 14 Pro Max",
      "iPhone 14 Pro",
      "iPhone 14 Plus",
      "iPhone 14",
      "iPhone 13 Pro Max",
      "iPhone 13 Pro",
      "iPhone 13 mini",
      "iPhone 13",
      "iPhone 12 Pro Max",
      "iPhone 12 Pro",
      "iPhone 12 mini",
      "iPhone 12",
      "iPhone 11 Pro Max",
      "iPhone 11 Pro",
      "iPhone 11",
      "iPhone XS Max",
      "iPhone XS",
      "iPhone XR",
      "iPhone X",
      "iPhone 8 Plus",
      "iPhone 8",
      "iPhone 7 Plus",
      "iPhone 7",
      "iPhone 6s Plus",
      "iPhone 6s",
      "iPhone 6 Plus",
      "iPhone 6",
      "iPhone SE 3rd Gen",
      "iPhone SE 2nd Gen",
      "iPhone SE 1st Gen",
      "iPhone 5s",
      "iPhone 5c",
      "iPhone 5",
      "iPhone 4s",
      "iPhone 4",
    ],
  },
  {
    name: "Samsung",
    sortOrder: 2,
    families: [
      "Galaxy S25 Ultra",
      "Galaxy S25+",
      "Galaxy S25",
      "Galaxy S25 FE",
      "Galaxy S24 Ultra",
      "Galaxy S24+",
      "Galaxy S24",
      "Galaxy S24 FE",
      "Galaxy S23 Ultra",
      "Galaxy S23+",
      "Galaxy S23",
      "Galaxy S23 FE",
      "Galaxy S22 Ultra",
      "Galaxy S22+",
      "Galaxy S22",
      "Galaxy S22 FE",
      "Galaxy S21 Ultra",
      "Galaxy S21+",
      "Galaxy S21",
      "Galaxy S21 FE",
      "Galaxy S20 Ultra",
      "Galaxy S20+",
      "Galaxy S20",
      "Galaxy S20 FE",
      "Galaxy S10+",
      "Galaxy S10",
      "Galaxy S10e",
      "Galaxy S9+",
      "Galaxy S9",
      "Galaxy S8+",
      "Galaxy S8",
      "Galaxy S7 Edge",
      "Galaxy S7",
      "Galaxy S6 Edge",
      "Galaxy S6",
      "Galaxy A06",
      "Galaxy A05s",
      "Galaxy A05",
      "Galaxy A04s",
      "Galaxy A04",
      "Galaxy A03s",
      "Galaxy A03",
      "Galaxy A02s",
      "Galaxy A02",
      "Galaxy A01",
      "Galaxy A16",
      "Galaxy A15",
      "Galaxy A14",
      "Galaxy A13",
      "Galaxy A12",
      "Galaxy A11",
      "Galaxy A10s",
      "Galaxy A10",
      "Galaxy A26",
      "Galaxy A25",
      "Galaxy A24",
      "Galaxy A23",
      "Galaxy A22",
      "Galaxy A21s",
      "Galaxy A20s",
      "Galaxy A20",
      "Galaxy A36",
      "Galaxy A35",
      "Galaxy A34",
      "Galaxy A33",
      "Galaxy A32",
      "Galaxy A31",
      "Galaxy A30s",
      "Galaxy A30",
      "Galaxy A56",
      "Galaxy A55",
      "Galaxy A54",
      "Galaxy A53",
      "Galaxy A52s",
      "Galaxy A52",
      "Galaxy A51",
      "Galaxy A50s",
      "Galaxy A50",
      "Galaxy A73",
      "Galaxy A72",
      "Galaxy A71",
      "Galaxy A70",
      "Galaxy M55",
      "Galaxy M54",
      "Galaxy M53",
      "Galaxy M52",
      "Galaxy M51",
      "Galaxy M35",
      "Galaxy M34",
      "Galaxy M33",
      "Galaxy M32",
      "Galaxy M31",
      "Galaxy M30s",
      "Galaxy M30",
      "Galaxy M15",
      "Galaxy M14",
      "Galaxy M13",
      "Galaxy M12",
      "Galaxy M11",
      "Galaxy M10",
      "Galaxy F55",
      "Galaxy F54",
      "Galaxy F34",
      "Galaxy F23",
      "Galaxy F22",
      "Galaxy F14",
      "Galaxy F13",
      "Galaxy F12",
      "Galaxy Note 20 Ultra",
      "Galaxy Note 20",
      "Galaxy Note 10+",
      "Galaxy Note 10",
      "Galaxy Note 9",
      "Galaxy Note 8",
      "Galaxy Z Fold6",
      "Galaxy Z Fold5",
      "Galaxy Z Fold4",
      "Galaxy Z Fold3",
      "Galaxy Z Fold2",
      "Galaxy Fold",
      "Galaxy Z Flip6",
      "Galaxy Z Flip5",
      "Galaxy Z Flip4",
      "Galaxy Z Flip3",
      "Galaxy Z Flip",
      "Galaxy XCover 7",
      "Galaxy XCover 6 Pro",
      "Galaxy XCover Pro",
    ],
  },
  {
    name: "Xiaomi",
    sortOrder: 3,
    families: [
      "Xiaomi 15 Ultra",
      "Xiaomi 15 Pro",
      "Xiaomi 15",
      "Xiaomi 15 Lite",
      "Xiaomi 14 Ultra",
      "Xiaomi 14 Pro",
      "Xiaomi 14",
      "Xiaomi 14 Lite",
      "Xiaomi 13 Ultra",
      "Xiaomi 13 Pro",
      "Xiaomi 13",
      "Xiaomi 13 Lite",
      "Xiaomi 12 Ultra",
      "Xiaomi 12 Pro",
      "Xiaomi 12",
      "Xiaomi 12 Lite",
      "Xiaomi 11 Ultra",
      "Xiaomi 11 Pro",
      "Xiaomi 11",
      "Xiaomi 11 Lite",
      "Xiaomi 10 Ultra",
      "Xiaomi 10 Pro",
      "Xiaomi 10",
      "Xiaomi 10 Lite",
      "Xiaomi 9 Ultra",
      "Xiaomi 9 Pro",
      "Xiaomi 9",
      "Xiaomi 9 Lite",
      "Xiaomi 14T Pro",
      "Xiaomi 14T",
      "Xiaomi 13T Pro",
      "Xiaomi 13T",
      "Xiaomi 12T Pro",
      "Xiaomi 12T",
      "Xiaomi 11T Pro",
      "Xiaomi 11T",
      "Mi 11 Ultra",
      "Mi 11 Pro",
      "Mi 11",
      "Mi 11 Lite",
      "Mi 10T Pro",
      "Mi 10T",
      "Mi 10 Lite",
      "Mi Note 10 Pro",
      "Mi Note 10",
      "Mi A3",
      "Mi A2",
      "Mi A1",
      "Xiaomi MIX 4",
      "Mi MIX 3",
      "Mi MIX 2S",
    ],
  },
  {
    name: "Redmi",
    sortOrder: 4,
    families: [
      "Redmi Note 14 Pro+",
      "Redmi Note 14 Pro",
      "Redmi Note 14",
      "Redmi Note 14S",
      "Redmi Note 13 Pro+",
      "Redmi Note 13 Pro",
      "Redmi Note 13",
      "Redmi Note 13S",
      "Redmi Note 12 Pro+",
      "Redmi Note 12 Pro",
      "Redmi Note 12",
      "Redmi Note 12S",
      "Redmi Note 11 Pro+",
      "Redmi Note 11 Pro",
      "Redmi Note 11",
      "Redmi Note 11S",
      "Redmi Note 10 Pro+",
      "Redmi Note 10 Pro",
      "Redmi Note 10",
      "Redmi Note 10S",
      "Redmi Note 9 Pro+",
      "Redmi Note 9 Pro",
      "Redmi Note 9",
      "Redmi Note 9S",
      "Redmi Note 8 Pro+",
      "Redmi Note 8 Pro",
      "Redmi Note 8",
      "Redmi Note 8S",
      "Redmi Note 7 Pro+",
      "Redmi Note 7 Pro",
      "Redmi Note 7",
      "Redmi Note 7S",
      "Redmi 14C",
      "Redmi 13C",
      "Redmi 12C",
      "Redmi 10C",
      "Redmi 9C",
      "Redmi 9A",
      "Redmi 8A",
      "Redmi A5",
      "Redmi A3",
      "Redmi A2",
      "Redmi A1",
      "Redmi 13",
      "Redmi 12",
      "Redmi 10",
      "Redmi 9",
      "Redmi 8",
      "Redmi K70",
      "Redmi K60",
      "Redmi K50",
      "Redmi K40",
    ],
  },
  {
    name: "Poco",
    sortOrder: 5,
    families: [
      "POCO F7 Ultra",
      "POCO F7 Pro",
      "POCO F7",
      "POCO F6 Pro",
      "POCO F6",
      "POCO F5 Pro",
      "POCO F5",
      "POCO F4 GT",
      "POCO F4",
      "POCO F3",
      "POCO X7 Pro",
      "POCO X7",
      "POCO X6 Pro",
      "POCO X6",
      "POCO X5 Pro",
      "POCO X5",
      "POCO X4 Pro",
      "POCO X4 GT",
      "POCO X3 Pro",
      "POCO X3 NFC",
      "POCO M7 Pro 5G",
      "POCO M7",
      "POCO M6 Pro",
      "POCO M6",
      "POCO M5s",
      "POCO M5",
      "POCO M4 Pro",
      "POCO M4 5G",
      "POCO M3 Pro",
      "POCO M3",
      "POCO C85",
      "POCO C75",
      "POCO C65",
      "POCO C55",
      "POCO C51",
      "POCO C40",
      "POCO C31",
    ],
  },
  {
    name: "Oppo",
    sortOrder: 6,
    families: [
      "OPPO Find X9 Ultra",
      "OPPO Find X9s",
      "OPPO Find X8 Pro",
      "OPPO Find X8",
      "OPPO Find X7 Ultra",
      "OPPO Find X7",
      "OPPO Find X6 Pro",
      "OPPO Find X6",
      "OPPO Find X5 Pro",
      "OPPO Find X5",
      "OPPO Find N3",
      "OPPO Find N3 Flip",
      "OPPO Find N2",
      "OPPO Find N2 Flip",
      "OPPO Find X3 Pro",
      "OPPO Find X2 Pro",
      "OPPO Reno15 Pro",
      "OPPO Reno15",
      "OPPO Reno15 F",
      "OPPO Reno14 Pro",
      "OPPO Reno14",
      "OPPO Reno14 F",
      "OPPO Reno13 Pro",
      "OPPO Reno13",
      "OPPO Reno13 F",
      "OPPO Reno12 Pro",
      "OPPO Reno12",
      "OPPO Reno12 F",
      "OPPO Reno11 Pro",
      "OPPO Reno11",
      "OPPO Reno11 F",
      "OPPO Reno10 Pro",
      "OPPO Reno10",
      "OPPO Reno10 F",
      "OPPO Reno9 Pro",
      "OPPO Reno9",
      "OPPO Reno9 F",
      "OPPO Reno8 Pro",
      "OPPO Reno8",
      "OPPO Reno8 F",
      "OPPO Reno7 Pro",
      "OPPO Reno7",
      "OPPO Reno7 F",
      "OPPO Reno6 Pro",
      "OPPO Reno6",
      "OPPO Reno6 F",
      "OPPO Reno5 Pro",
      "OPPO Reno5",
      "OPPO Reno5 F",
      "OPPO Reno4 Pro",
      "OPPO Reno4",
      "OPPO Reno4 F",
      "OPPO Reno3 Pro",
      "OPPO Reno3",
      "OPPO Reno3 F",
      "OPPO Reno2 Pro",
      "OPPO Reno2",
      "OPPO Reno2 F",
      "OPPO A98",
      "OPPO A96",
      "OPPO A95",
      "OPPO A94",
      "OPPO A93",
      "OPPO A92",
      "OPPO A91",
      "OPPO A80",
      "OPPO A79",
      "OPPO A78",
      "OPPO A77",
      "OPPO A76",
      "OPPO A74",
      "OPPO A73",
      "OPPO A72",
      "OPPO A71",
      "OPPO A60",
      "OPPO A59",
      "OPPO A58",
      "OPPO A57",
      "OPPO A56",
      "OPPO A55",
      "OPPO A54",
      "OPPO A53",
      "OPPO A52",
      "OPPO A38",
      "OPPO A37",
      "OPPO A18",
      "OPPO A17",
      "OPPO A16",
      "OPPO A15",
      "OPPO A12",
      "OPPO A9",
      "OPPO A5",
    ],
  },
  {
    name: "Realme",
    sortOrder: 7,
    families: [
      "realme GT 8 Pro",
      "realme GT 7 Pro",
      "realme GT 7",
      "realme GT 6",
      "realme GT 6T",
      "realme GT 5",
      "realme GT 3",
      "realme GT Neo 6",
      "realme GT Neo 5",
      "realme GT Neo 3",
      "realme GT Neo 2",
      "realme GT Master Edition",
      "realme 14 Pro+",
      "realme 14 Pro",
      "realme 14",
      "realme 13 Pro+",
      "realme 13 Pro",
      "realme 13",
      "realme 12 Pro+",
      "realme 12 Pro",
      "realme 12",
      "realme 11 Pro+",
      "realme 11 Pro",
      "realme 11",
      "realme 10 Pro+",
      "realme 10 Pro",
      "realme 10",
      "realme 9 Pro+",
      "realme 9 Pro",
      "realme 9",
      "realme 8 Pro+",
      "realme 8 Pro",
      "realme 8",
      "realme 7 Pro+",
      "realme 7 Pro",
      "realme 7",
      "realme 6 Pro+",
      "realme 6 Pro",
      "realme 6",
      "realme C75",
      "realme C67",
      "realme C65",
      "realme C63",
      "realme C61",
      "realme C55",
      "realme C53",
      "realme C51",
      "realme C35",
      "realme C33",
      "realme C31",
      "realme C30",
      "realme C25",
      "realme C21",
      "realme C15",
      "realme C12",
      "realme C11",
      "realme Narzo 70 Pro",
      "realme Narzo 70",
      "realme Narzo 60 Pro",
      "realme Narzo 60",
      "realme Narzo 50 Pro",
      "realme Narzo 50",
      "realme Narzo 30 Pro",
      "realme Narzo 30",
      "realme Narzo 20 Pro",
      "realme Narzo 20",
      "realme Note 60",
      "realme Note 50",
      "realme P3 Ultra",
      "realme P3 Pro",
      "realme P3",
      "realme P2 Pro",
      "realme P1 Pro",
      "realme P1",
    ],
  },
  {
    name: "Vivo",
    sortOrder: 8,
    families: [
      "vivo X300 Pro",
      "vivo X300",
      "vivo X200 Pro",
      "vivo X200",
      "vivo X100 Pro",
      "vivo X100",
      "vivo X90 Pro",
      "vivo X90",
      "vivo X80 Pro",
      "vivo X80",
      "vivo X70 Pro",
      "vivo X70",
      "vivo X60 Pro",
      "vivo X60",
      "vivo X50 Pro",
      "vivo X50",
      "vivo V70 Pro",
      "vivo V70",
      "vivo V70e",
      "vivo V60 Pro",
      "vivo V60",
      "vivo V60e",
      "vivo V50 Pro",
      "vivo V50",
      "vivo V50e",
      "vivo V40 Pro",
      "vivo V40",
      "vivo V40e",
      "vivo V30 Pro",
      "vivo V30",
      "vivo V30e",
      "vivo V29 Pro",
      "vivo V29",
      "vivo V29e",
      "vivo V27 Pro",
      "vivo V27",
      "vivo V27e",
      "vivo V25 Pro",
      "vivo V25",
      "vivo V25e",
      "vivo V23 Pro",
      "vivo V23",
      "vivo V23e",
      "vivo V21 Pro",
      "vivo V21",
      "vivo V21e",
      "vivo V20 Pro",
      "vivo V20",
      "vivo V20e",
      "vivo V19 Pro",
      "vivo V19",
      "vivo V19e",
      "vivo V17 Pro",
      "vivo V17",
      "vivo V17e",
      "vivo V15 Pro",
      "vivo V15",
      "vivo V15e",
      "vivo Y39",
      "vivo Y38",
      "vivo Y36",
      "vivo Y35",
      "vivo Y33s",
      "vivo Y33",
      "vivo Y28",
      "vivo Y27",
      "vivo Y22s",
      "vivo Y22",
      "vivo Y21s",
      "vivo Y21",
      "vivo Y20s",
      "vivo Y20",
      "vivo Y19",
      "vivo Y17",
      "vivo Y16",
      "vivo Y15",
      "vivo Y12s",
      "vivo Y12",
      "vivo Y11",
      "vivo T3 Pro",
      "vivo T3",
      "vivo T2 Pro",
      "vivo T2",
      "vivo S18 Pro",
      "vivo S18",
      "vivo S17 Pro",
      "vivo S17",
    ],
  },
  {
    name: "Huawei",
    sortOrder: 9,
    families: [
      "HUAWEI Mate 80 Pro",
      "HUAWEI Mate 80",
      "HUAWEI Mate 70 Pro",
      "HUAWEI Mate 70",
      "HUAWEI Mate 60 Pro",
      "HUAWEI Mate 60",
      "HUAWEI Mate 50 Pro",
      "HUAWEI Mate 50",
      "HUAWEI Mate 40 Pro",
      "HUAWEI Mate 40",
      "HUAWEI Mate 30 Pro",
      "HUAWEI Mate 30",
      "HUAWEI Mate 20 Pro",
      "HUAWEI Mate 20",
      "HUAWEI Mate 10 Pro",
      "HUAWEI Mate 10",
      "HUAWEI Mate X7",
      "HUAWEI Mate X6",
      "HUAWEI Mate X5",
      "HUAWEI Mate X3",
      "HUAWEI Mate X2",
      "HUAWEI Pura 80 Ultra",
      "HUAWEI Pura 80 Pro",
      "HUAWEI Pura 80",
      "HUAWEI Pura 70 Ultra",
      "HUAWEI Pura 70 Pro",
      "HUAWEI Pura 70",
      "HUAWEI P60 Pro",
      "HUAWEI P60",
      "HUAWEI P50 Pro",
      "HUAWEI P50",
      "HUAWEI P40 Pro",
      "HUAWEI P40",
      "HUAWEI P30 Pro",
      "HUAWEI P30",
      "HUAWEI P20 Pro",
      "HUAWEI P20",
      "HUAWEI nova 13 Pro",
      "HUAWEI nova 13",
      "HUAWEI nova 13i",
      "HUAWEI nova 12 Pro",
      "HUAWEI nova 12",
      "HUAWEI nova 12i",
      "HUAWEI nova 11 Pro",
      "HUAWEI nova 11",
      "HUAWEI nova 11i",
      "HUAWEI nova 10 Pro",
      "HUAWEI nova 10",
      "HUAWEI nova 10i",
      "HUAWEI nova 9 Pro",
      "HUAWEI nova 9",
      "HUAWEI nova 9i",
      "HUAWEI nova 8 Pro",
      "HUAWEI nova 8",
      "HUAWEI nova 8i",
      "HUAWEI nova 7 Pro",
      "HUAWEI nova 7",
      "HUAWEI nova 7i",
      "HUAWEI nova 5 Pro",
      "HUAWEI nova 5",
      "HUAWEI nova 5i",
      "HUAWEI nova 3 Pro",
      "HUAWEI nova 3",
      "HUAWEI nova 3i",
      "HUAWEI Y90",
      "HUAWEI Y70",
      "HUAWEI Y9a",
      "HUAWEI Y9s",
      "HUAWEI Y9 Prime",
      "HUAWEI Y8p",
      "HUAWEI Y8s",
      "HUAWEI Y7a",
      "HUAWEI Y7p",
      "HUAWEI Y6p",
      "HUAWEI Y6s",
      "HUAWEI Y5p",
    ],
  },
  {
    name: "Honor",
    sortOrder: 10,
    families: [
      "HONOR Magic8 Pro",
      "HONOR Magic8",
      "HONOR Magic7 Pro",
      "HONOR Magic7",
      "HONOR Magic6 Pro",
      "HONOR Magic6",
      "HONOR Magic5 Pro",
      "HONOR Magic5",
      "HONOR Magic4 Pro",
      "HONOR Magic4",
      "HONOR Magic V5",
      "HONOR Magic V3",
      "HONOR Magic V2",
      "HONOR Magic Vs",
      "HONOR Magic V",
      "HONOR 600 Pro",
      "HONOR 600",
      "HONOR 400 Pro",
      "HONOR 400",
      "HONOR 300 Pro",
      "HONOR 300",
      "HONOR 200 Pro",
      "HONOR 200",
      "HONOR 100 Pro",
      "HONOR 100",
      "HONOR 90",
      "HONOR 90 Lite",
      "HONOR 70",
      "HONOR 50",
      "HONOR 20",
      "HONOR 10",
      "HONOR X9d",
      "HONOR X9c",
      "HONOR X9b",
      "HONOR X9a",
      "HONOR X8d",
      "HONOR X8c",
      "HONOR X8b",
      "HONOR X8a",
      "HONOR X7d",
      "HONOR X7c",
      "HONOR X7b",
      "HONOR X7a",
      "HONOR X6d",
      "HONOR X6c",
      "HONOR X6b",
      "HONOR X6a",
      "HONOR X5 Plus",
      "HONOR X5",
    ],
  },
  {
    name: "Infinix",
    sortOrder: 11,
    families: [
      "Infinix GT 30 Pro",
      "Infinix GT 20 Pro",
      "Infinix GT 10 Pro",
      "Infinix ZERO 50 Pro",
      "Infinix ZERO 50",
      "Infinix ZERO 40 Pro",
      "Infinix ZERO 40",
      "Infinix ZERO 30 Pro",
      "Infinix ZERO 30",
      "Infinix ZERO 20 Pro",
      "Infinix ZERO 20",
      "Infinix ZERO 10 Pro",
      "Infinix ZERO 10",
      "Infinix ZERO 8 Pro",
      "Infinix ZERO 8",
      "Infinix NOTE 60 Pro",
      "Infinix NOTE 60",
      "Infinix NOTE 50 Pro",
      "Infinix NOTE 50",
      "Infinix NOTE 40 Pro",
      "Infinix NOTE 40",
      "Infinix NOTE 30 Pro",
      "Infinix NOTE 30",
      "Infinix NOTE 12 Pro",
      "Infinix NOTE 12",
      "Infinix NOTE 11 Pro",
      "Infinix NOTE 11",
      "Infinix NOTE 10 Pro",
      "Infinix NOTE 10",
      "Infinix NOTE 8 Pro",
      "Infinix NOTE 8",
      "Infinix HOT 60 Pro",
      "Infinix HOT 60",
      "Infinix HOT 50 Pro",
      "Infinix HOT 50",
      "Infinix HOT 40 Pro",
      "Infinix HOT 40",
      "Infinix HOT 30 Pro",
      "Infinix HOT 30",
      "Infinix HOT 20 Pro",
      "Infinix HOT 20",
      "Infinix HOT 12 Pro",
      "Infinix HOT 12",
      "Infinix HOT 11 Pro",
      "Infinix HOT 11",
      "Infinix HOT 10 Pro",
      "Infinix HOT 10",
      "Infinix HOT 9 Pro",
      "Infinix HOT 9",
      "Infinix HOT 8 Pro",
      "Infinix HOT 8",
      "Infinix SMART 10",
      "Infinix SMART 9",
      "Infinix SMART 8",
      "Infinix SMART 7",
      "Infinix SMART 6",
      "Infinix SMART 5",
      "Infinix SMART 4",
    ],
  },
  {
    name: "Tecno",
    sortOrder: 12,
    families: [
      "TECNO PHANTOM V Fold2",
      "TECNO PHANTOM V Fold",
      "TECNO PHANTOM V Flip2",
      "TECNO PHANTOM V Flip",
      "TECNO PHANTOM X2 Pro",
      "TECNO PHANTOM X2",
      "TECNO PHANTOM X",
      "TECNO CAMON 40 Pro",
      "TECNO CAMON 40",
      "TECNO CAMON 30 Pro",
      "TECNO CAMON 30",
      "TECNO CAMON 20 Pro",
      "TECNO CAMON 20",
      "TECNO CAMON 19 Pro",
      "TECNO CAMON 19",
      "TECNO CAMON 18 Pro",
      "TECNO CAMON 18",
      "TECNO CAMON 17 Pro",
      "TECNO CAMON 17",
      "TECNO CAMON 16 Pro",
      "TECNO CAMON 16",
      "TECNO CAMON 15 Pro",
      "TECNO CAMON 15",
      "TECNO SPARK 40 Pro",
      "TECNO SPARK 40",
      "TECNO SPARK 30 Pro",
      "TECNO SPARK 30",
      "TECNO SPARK 20 Pro",
      "TECNO SPARK 20",
      "TECNO SPARK 10 Pro",
      "TECNO SPARK 10",
      "TECNO SPARK 9 Pro",
      "TECNO SPARK 9",
      "TECNO SPARK 8 Pro",
      "TECNO SPARK 8",
      "TECNO SPARK 7 Pro",
      "TECNO SPARK 7",
      "TECNO POVA 7 Pro",
      "TECNO POVA 7",
      "TECNO POVA 6 Pro",
      "TECNO POVA 6",
      "TECNO POVA 5 Pro",
      "TECNO POVA 5",
      "TECNO POVA 4 Pro",
      "TECNO POVA 4",
      "TECNO POVA 3",
      "TECNO POVA 2",
      "TECNO POP 9",
      "TECNO POP 8",
      "TECNO POP 7",
      "TECNO POP 6",
      "TECNO POP 5",
      "TECNO POP 4",
    ],
  },
  {
    name: "Itel",
    sortOrder: 13,
    families: [
      "itel S25 Ultra",
      "itel S25",
      "itel S24",
      "itel S23+",
      "itel S23",
      "itel S18",
      "itel S17",
      "itel S16",
      "itel P70",
      "itel P65",
      "itel P55",
      "itel P40",
      "itel P38",
      "itel P37",
      "itel A95",
      "itel A90",
      "itel A80",
      "itel A70",
      "itel A60s",
      "itel A60",
      "itel A58",
      "itel A49",
      "itel A48",
      "itel A27",
      "itel A25",
      "itel Vision 3",
      "itel Vision 2",
      "itel Vision 1",
    ],
  },
  {
    name: "Nokia",
    sortOrder: 14,
    families: [
      "Nokia G60",
      "Nokia G50",
      "Nokia G42",
      "Nokia G22",
      "Nokia G21",
      "Nokia G20",
      "Nokia X30",
      "Nokia X20",
      "Nokia X10",
      "Nokia C32",
      "Nokia C31",
      "Nokia C30",
      "Nokia C22",
      "Nokia C21",
      "Nokia C20",
      "Nokia C10",
      "Nokia 8.3",
      "Nokia 7.2",
      "Nokia 6.2",
      "Nokia 5.4",
      "Nokia 5.3",
      "Nokia 4.2",
      "Nokia 3.4",
      "Nokia 3.2",
      "Nokia 2.4",
      "Nokia 2.3",
      "Nokia 1.4",
      "Nokia 1.3",
    ],
  },
  {
    name: "Motorola",
    sortOrder: 15,
    families: [
      "Motorola Edge 60 Ultra",
      "Motorola Edge 60 Pro",
      "Motorola Edge 60",
      "Motorola Edge 50 Ultra",
      "Motorola Edge 50 Pro",
      "Motorola Edge 50",
      "Motorola Edge 40 Ultra",
      "Motorola Edge 40 Pro",
      "Motorola Edge 40",
      "Motorola Edge 30 Ultra",
      "Motorola Edge 30 Pro",
      "Motorola Edge 30",
      "Motorola Edge 20 Ultra",
      "Motorola Edge 20 Pro",
      "Motorola Edge 20",
      "Moto G86",
      "Moto G85",
      "Moto G84",
      "Moto G73",
      "Moto G72",
      "Moto G62",
      "Moto G60",
      "Moto G54",
      "Moto G53",
      "Moto G52",
      "Moto G51",
      "Moto G42",
      "Moto G41",
      "Moto G32",
      "Moto G31",
      "Moto G30",
      "Moto G24",
      "Moto G23",
      "Moto G22",
      "Moto G14",
      "Moto G13",
      "Moto G10",
      "Moto E40",
      "Moto E32",
      "Moto E22",
      "Moto E20",
      "Motorola Razr 50 Ultra",
      "Motorola Razr 50",
      "Motorola Razr 40 Ultra",
      "Motorola Razr 40",
      "Motorola Razr 2022",
    ],
  },
  {
    name: "OnePlus",
    sortOrder: 16,
    families: [
      "OnePlus 13",
      "OnePlus 13R",
      "OnePlus 12",
      "OnePlus 12R",
      "OnePlus 11",
      "OnePlus 10 Pro",
      "OnePlus 10T",
      "OnePlus 9 Pro",
      "OnePlus 9",
      "OnePlus 8 Pro",
      "OnePlus 8T",
      "OnePlus 8",
      "OnePlus 7T Pro",
      "OnePlus 7T",
      "OnePlus 7 Pro",
      "OnePlus 7",
      "OnePlus 6T",
      "OnePlus 6",
      "OnePlus Nord 4",
      "OnePlus Nord 3",
      "OnePlus Nord 2T",
      "OnePlus Nord 2",
      "OnePlus Nord CE4",
      "OnePlus Nord CE3",
      "OnePlus Nord CE2",
      "OnePlus Nord N30",
      "OnePlus Nord N20",
      "OnePlus Ace 3",
      "OnePlus Ace 2",
    ],
  },
  {
    name: "Google Pixel",
    sortOrder: 17,
    families: [
      "Google Pixel 9 Pro XL",
      "Google Pixel 9 Pro",
      "Google Pixel 9",
      "Google Pixel 9a",
      "Google Pixel 8 Pro XL",
      "Google Pixel 8 Pro",
      "Google Pixel 8",
      "Google Pixel 8a",
      "Google Pixel 7 Pro XL",
      "Google Pixel 7 Pro",
      "Google Pixel 7",
      "Google Pixel 7a",
      "Google Pixel 6 Pro XL",
      "Google Pixel 6 Pro",
      "Google Pixel 6",
      "Google Pixel 6a",
      "Google Pixel 5",
      "Google Pixel 4a",
      "Google Pixel 4 XL",
      "Google Pixel 4",
      "Google Pixel 3a XL",
      "Google Pixel 3a",
      "Google Pixel 3 XL",
      "Google Pixel 3",
    ],
  },
  {
    name: "Sony",
    sortOrder: 18,
    families: [
      "Sony Xperia 1 VI",
      "Sony Xperia 1 V",
      "Sony Xperia 1 IV",
      "Sony Xperia 1 III",
      "Sony Xperia 5 V",
      "Sony Xperia 5 IV",
      "Sony Xperia 5 III",
      "Sony Xperia 10 VI",
      "Sony Xperia 10 V",
      "Sony Xperia 10 IV",
      "Sony Xperia 10 III",
      "Sony Xperia L4",
      "Sony Xperia L3",
      "Sony Xperia XZ3",
      "Sony Xperia XZ2",
      "Sony Xperia XA2",
    ],
  },
  {
    name: "LG",
    sortOrder: 19,
    families: [
      "LG Velvet",
      "LG Wing",
      "LG G8 ThinQ",
      "LG G7 ThinQ",
      "LG G6",
      "LG V60 ThinQ",
      "LG V50 ThinQ",
      "LG V40 ThinQ",
      "LG V30",
      "LG K62",
      "LG K52",
      "LG K42",
      "LG K40",
      "LG K20",
      "LG Q60",
      "LG Q7",
    ],
  },
  {
    name: "ZTE / Nubia",
    sortOrder: 20,
    families: [
      "ZTE Blade A75",
      "ZTE Blade A73",
      "ZTE Blade A72",
      "ZTE Blade A52",
      "ZTE Blade V40",
      "ZTE Blade V30",
      "ZTE Axon 40 Ultra",
      "ZTE Axon 30",
      "ZTE Axon 20",
      "Nubia RedMagic 9 Pro",
      "Nubia RedMagic 8 Pro",
      "Nubia RedMagic 7",
      "Nubia RedMagic 6",
      "Nubia Z60 Ultra",
      "Nubia Z50",
    ],
  },
  {
    name: "Condor",
    sortOrder: 21,
    families: [
      "Condor Allure A100",
      "Condor Allure A55",
      "Condor Allure M3",
      "Condor Allure X",
      "Condor Plume L8 Pro",
      "Condor Plume L6 Pro",
      "Condor Plume P8 Pro",
      "Condor Griffe T9",
      "Condor Griffe T8",
      "Condor Griffe T7",
      "Condor Griffe G6",
      "Condor Griffe G5",
    ],
  },
  {
    name: "Autre",
    sortOrder: 99,
    families: [
      "HTC U23 Pro",
      "HTC U12+",
      "HTC U11",
      "HTC 10",
      "BlackBerry KEY2",
      "BlackBerry KEYone",
      "BlackBerry Priv",
      "Alcatel 1S",
      "Alcatel 1SE",
      "Alcatel 3X",
      "Alcatel 5V",
      "Wiko View5",
      "Wiko View4",
      "Wiko Y80",
      "Wiko Y60",
      "Meizu 21",
      "Meizu 20",
      "Meizu 18",
      "Meizu 16th",
      "Lenovo K14",
      "Lenovo K13",
      "Lenovo K12",
      "Lenovo Z6 Pro",
      "Lenovo Legion Phone Duel",
    ],
  },
];
